namespace ImpactLab.Core.Reporting.Templates;

public sealed record ReportTemplate(
    string Id,
    string Name,
    string Title,
    IReadOnlyList<ReportTemplateSection> Sections,
    string FooterText = "Generated by ImpactLab"
);
